### ISSUE TITLE
Propagate fuzzing options to the OSS-Fuzz package, through the creation of the options file.

### ISSUE THREAD

**Issue by stefanbucur** [bazelbuild/rules_fuzzing#104]

**Comment by fmeum** [comment]
Is there more that needs to be done here now that #148 has been merged? `.options` files are not exposed via the `*_fuzz_test` macros yet, but this also doesn't seem to be needed for C++ fuzz tests since `max_len` should rather be implemented in the fuzz test directly.

**Comment by stefanbucur** [comment]
You're right, I think this is now addressed. Thanks!
