### ISSUE TITLE
Add an end-to-end test for the OSS-Fuzz integration

### ISSUE THREAD

**Issue by stefanbucur** [bazelbuild/rules_fuzzing#105]
@oliverchang In https://github.com/bazelbuild/rules_fuzzing/pull/96#pullrequestreview-562272981 you mentioned:

> Perhaps we can have a GitHub action for this repo which checks out OSS-Fuzz at the latest revision and builds the test project? Seems like something that would fit better in this repo.

Just to confirm: would it be okay to submit a test project to the OSS-Fuzz repo (e.g., `projects/bazel-rules-fuzzing`) that runs the fuzzing examples in this repo? Is there a way to mark the project as "test only" so it doesn't run on the OSS-Fuzz infrastructure (it would use up resources unnecessarily)?

**Comment by oliverchang** [comment]
Yep, we already have similar projects such as https://github.com/google/oss-fuzz/blob/2cf181aa323c6bdeb1073622f0642782eb66acf9/projects/cifuzz-example/project.yaml#L5. You just need to specify "disabled: true"

**Comment by stefanbucur** [comment]
Fixed in #117.
