### ISSUE TITLE
Dictionary concatenation

### ISSUE THREAD

**Issue by asraa** [bazelbuild/rules_fuzzing#124]
## Expected Behavior
Expect that two dictionary files 
```
a.dict
# Dictionary A
abc
```
and
```
b.dict
# Dictionary B
def
```
are successfully concatenated together.

## Actual Behavior
It seems like if file A doesn't have an end new line, then https://github.com/bazelbuild/rules_fuzzing/blob/547127916d662d729ed62164bb88edbff27e215b/fuzzing/tools/validate_dict.py#L43 won't write one, so the resulting dictionary becomes

```
# Dictionary A
abc# Dictionary B
def
```
which isn't valid.

I originally saw the issue in oss-fuzz logs:
```
Step #14: ParseDictionaryFile: error in line 24
Step #14: 		"%HOSTNAME%"# Dictionary to populate HeaderValueOptions
```

**Comment by stefanbucur** [comment]
Whoops, thanks for spotting this. Let me take a look.
