### ISSUE TITLE
Control instrumentation of external dependencies in Bazel project.

### ISSUE THREAD

**Issue by DavidKorczynski** [bazelbuild/rules_fuzzing#132]
I am working on the Envoy Bazel build atm, which is integrated into OSS-Fuzz. We have an issue in that the fuzzer flags are propagated to the dependencies and external libraries of the project, and we would prefer if some of these dependencies were not compiled with instrumentation flags. Is there any way to specify this for a given library? 
Say we declare a library as follows:
```
cc_library(
    name = "sqlparser",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob([
        "include/**/*.h",
        "src/**/*.h",
    ]),
    defines = select({
        "@envoy//bazel:windows_x86_64": ["YY_NO_UNISTD_H"],
        "//conditions:default": [],
    }),
    visibility = ["//visibility:public"],
)
```
does `rules_fuzzing` support some way of building `sqlparser` without fuzz/sanitiser instrumentation?

**Comment by stefanbucur** [comment]
Yes, you should be able to achieve this with library-specific copts. Can you try adding the following to the cc_library definition:

```
copts = [
    "-fsanitize-coverage=0",
    "-fno-sanitize=all",
],
```

That should disable all the coverage instrumentation and sanitizer options on the source files of the library.

**Comment by DavidKorczynski** [comment]
> Yes, you should be able to achieve this with library-specific copts. Can you try adding the following to the cc_library definition:
> 
> ```
> copts = [
>     "-fsanitize-coverage=0",
>     "-fno-sanitize=all",
> ],
> ```
> 
> That should disable all the coverage instrumentation and sanitizer options on the source files of the library.
Thanks for the prompt reply! Will try this and get back to you!

**Comment by DavidKorczynski** [comment]
This worked like a charm. Thanks a lot!
