### ISSUE TITLE
Control instrumentation to compilation of protobuf code

### ISSUE THREAD

**Issue by DavidKorczynski** [bazelbuild/rules_fuzzing#133]
This is a follow-up of the issue here: https://github.com/bazelbuild/rules_fuzzing/issues/132

We face the problem of doing protobuf-based fuzzers and we would like to avoid instrumenting the protobuf-generated code with coverage instrumentation. The problem is, however, that `proto_library` does not let us specify which flags to pass down to when clang compiles our `pb.cc` files. As such, we cannot force the use of `copts` for our rules. 

To clarify:

We have this rule in Envoy:
```
envoy_proto_library(
    name = "h2_capture_fuzz_proto",
    srcs = [":h2_capture_fuzz.proto"],
)
```

The `envoy_proto_library` eventually calls into `proto_library` with the `srcs` files of `envoy_proto_library`, which gives us a rule `h2_capture_fuzz_proto_cc_proto`. The `h2_capture_fuzz_proto_cc_proto` rule will compile the generated `.pb.cc` code, and it is at this step we would like to enforce compilation with `-fsanitize-coverage=0`. 

Is this an issue that is familiar, and if so, do you have any advice on how to solve it?

There are two options we are considering atm:
`--proto_toolchain_for_cc` https://docs.bazel.build/versions/master/command-line-reference.html#flag--proto_toolchain_for_cc
and 
`--protocopt` https://docs.bazel.build/versions/master/command-line-reference.html#flag--protocopt

For cross-references: 
https://github.com/bazelbuild/rules_proto/issues/41
https://github.com/bazelbuild/rules_proto/issues/85

**Comment by stefanbucur** [comment]
If you want to avoid instrumenting the proto-generated files, you can override the instrumentation options per-file on the command line:

```
$ bazel build [...] --per_file_copt=^.*\.pb\.cc$@-fsanitize-coverage=0,-fno-sanitize=all
```

**Comment by DavidKorczynski** [comment]
Hm, I am having some troubles getting it to work. The options are not parsed to any of the files. Do you know of exceptions where the `per_file_opt` is disabled? My bazel command looks as follows:
```
bazel build -s --verbose_failures --dynamic_mode=off \
  --per_file_copt=^.*\.pb\.cc$@-fsanitize-coverage=0 --spawn_strategy=standalone --genrule_strategy=standalone \
  --local_cpu_resources=HOST_CPUS*0.32 \
  --//source/extensions/wasm_runtime/v8:enabled=false \
  --build_tag_filters=-no_asan --config=oss-fuzz \
  --copt=-D__SANITIZE_ADDRESS__ --copt=-DADDRESS_SANITIZER=1 --linkopt=-fsanitize=address \
  ${OSS_FUZZ_TARGETS[*]}
```

**Comment by stefanbucur** [comment]
I've just realized you might actually have to escape the regular expression in Bash. For example, the "$@" symbol might get inadvertently expanded by the shell.

**Comment by DavidKorczynski** [comment]
Ah of course - this works! Thank you so much!!
