### ISSUE TITLE
Build fails under OSX

### ISSUE THREAD

**Issue by eustas** [bazelbuild/rules_fuzzing#138]
## Expected Behavior
Instructions given in README should lead to successful build.

## Actual Behavior
Build fails on OSX:
```
ERROR: /private/var/tmp/_bazel_eustas/a0a6f697b808c7d2a5fc66d10631ebe1/external/rules_fuzzing/fuzzing/replay/BUILD:48:11: Compiling fuzzing/replay/status_util.cc failed: (Exit 1): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' ... (remaining 28 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' ... (remaining 28 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/rules_fuzzing/fuzzing/replay/status_util.cc:40:10: error: no viable conversion from returned value of type 'int' to function return type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >')
  return strerror_r(errno_value, error_str_buf, sizeof(error_str_buf));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:799:5: note: candidate constructor not viable: no known conversion from 'int' to 'const std::__1::basic_string<char> &' for 1st argument
    basic_string(const basic_string& __str);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:804:5: note: candidate constructor not viable: no known conversion from 'int' to 'std::__1::basic_string<char> &&' for 1st argument
    basic_string(basic_string&& __str)
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:817:5: note: candidate constructor template not viable: no known conversion from 'int' to 'const char *' for 1st argument
    basic_string(const _CharT* __s) : __r_(__default_init_tag(), __default_init_tag()) {
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:867:5: note: candidate constructor not viable: no known conversion from 'int' to 'initializer_list<char>' for 1st argument
    basic_string(initializer_list<_CharT> __il);
    ^
1 error generated.
```

## Steps to Reproduce the Problem

1. Follow README instructions

## Specifications

- Version: 0.1.3
- Platform: OSX

**Comment by eustas** [comment]
This problem seems to be also mentioned here: https://github.com/bazelbuild/bazel/issues/12888

**Comment by eustas** [comment]
I believe, it is better to use overload to deal with `strerror_r` API differences:
add functions `std::string WrapError(int)` and `std::string WrapError(char *)` and let compiler choose one of those.
Will try to prepare PR soon.

**Comment by eustas** [comment]
There are more problems after fixing the first one:
```
In file included from external/honggfuzz/libhfuzz/fetch.c:10:
external/honggfuzz/honggfuzz.h:371:5: error: unknown type name 'timer_t'; did you mean 'time_t'?
    timer_t timerId;
    ^~~~~~~
    time_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include/sys/_types/_time_t.h:31:33: note: 'time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
In file included from external/honggfuzz/libhfuzz/fetch.c:12:
external/honggfuzz/libhfcommon/log.h:29:50: error: expected identifier
enum llevel_t { FATAL = 0, ERROR, WARNING, INFO, DEBUG, HELP, HELP_BOLD };
                                                 ^
<command line>:2:15: note: expanded from here
#define DEBUG 1
              ^
2 errors generated.
```

**Comment by eustas** [comment]
And
```
external/honggfuzz/libhfuzz/instrument.c:8:10: fatal error: 'linux/mman.h' file not found
#include <linux/mman.h>
         ^~~~~~~~~~~~~~
1 error generated.
```
Perhaps honggfuzz should be done completely optional...

**Comment by eustas** [comment]
"-D_HF_ARCH_LINUX" option should not be added under OSX. Will try to fix that as well.

**Comment by eustas** [comment]
Done.
Now, hopefully the last error:
```
Undefined symbols for architecture x86_64:
  "_LLVMFuzzerInitialize", referenced from:
      _main in libreplay_main.lo(replay_main.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by eustas** [comment]
Similar problem seems to be reported here: https://github.com/google/honggfuzz/issues/115

**Comment by stefanbucur** [comment]
> ## Specifications
> * Version: 0.1.3
> * Platform: OSX

The fuzzing rules were launched with Linux support only, but I see you almost made them work on MacOS, too. Thanks a lot for the fixes!

> And
> 
> ```
> external/honggfuzz/libhfuzz/instrument.c:8:10: fatal error: 'linux/mman.h' file not found
> #include <linux/mman.h>
>          ^~~~~~~~~~~~~~
> 1 error generated.
> ```
> 
> Perhaps honggfuzz should be done completely optional...

Honggfuzz is already optional. If you're having trouble getting it running on MacOS and don't need it, you can disable it when initializing the workspace by using:

```
rules_fuzzing_dependencies(
    honggfuzz = False,
)
```

**Comment by eustas** [comment]
Nota Bene: under OSX project does not build, unless "-c opt" is specified, because of conflict of `DEBUG` defined as compiler argument and enum value in `honggfuzz/libhfcommon/log.h:29`

**Comment by stefanbucur** [comment]
> Nota Bene: under OSX project does not build, unless "-c opt" is specified, because of conflict of `DEBUG` defined as compiler argument and enum value in `honggfuzz/libhfcommon/log.h:29`

Although Mac OS is [listed as supported](https://github.com/google/honggfuzz#requirements) in Honggfuzz, there are a bunch of open issues with compilation errors there: https://github.com/google/honggfuzz/issues Does Honggfuzz run well in opt mode with Bazel?

**Comment by eustas** [comment]
Honggfuzz says it supports OSX, but not OSX + Bazel. However, Honggfuzz does not say to support fancy compilers, so it should be easy to use push/pop_macro pragmas to avoid the conflict. Going to prepare PR for Honggfuzz...

**Comment by eustas** [comment]
https://github.com/google/honggfuzz/pull/390

**Comment by stefanbucur** [comment]
MacOS is now part of our regression suite, so this should be fixed.
