### ISSUE TITLE
Add rules for the Jazzer fuzzer

### ISSUE THREAD

**Issue by chrismgrayftsinc** [bazelbuild/rules_fuzzing#141]
It appears that there are already BUILD rules for jazzer.  I wonder if it would make sense to integrate them into this repo for consistency.

**Comment by chrismgrayftsinc** [comment]
After trying to use the jazzer BUILD rules, they do not seem to work as an external project (they add dependencies to internal targets without a package name), so they would need to be adapted.

**Comment by fmeum** [comment]
I'm happy to make any changes to Jazzer required to get rules_fuzzing support. Since Jazzer is command-line compatible with libFuzzer and requires no instrumentation at compilation time, maybe all that's needed is to cleanly extract the language independent parts of the library.

**Comment by stefanbucur** [comment]
I think it would be great to get `java_fuzz_test()` support. I would be happy to review PRs adding this functionality.

Note that the `cc_fuzz_test` implementation strived to keep the C++-specific functionality separate from the rest of the fuzzing decorations (e.g., corpus, dictionary support), in anticipation of adding new languages in a clean way, so I expect we'd be able to reuse many of the existing components.
