### ISSUE TITLE
Incorrect SHA256 for v0.2.0.zip

### ISSUE THREAD

**Issue by grencez** [bazelbuild/rules_fuzzing#172]
## Expected Behavior
I'd expect a correct sha256 hash for v0.2.0.zip listed in the README and latest release (https://github.com/bazelbuild/rules_fuzzing/releases/tag/v0.2.0).

## Actual Behavior
The given hash (9b688a77b930e1842312d37b00fbb796b96323a2eb8362b2cfb68e7d6e74f860) is for the release's .tar.gz file, not the .zip. The .zip's contents do not differ (verified with `diff -r`), so the documented hash could just be updated to the correct one (127d7c45e9b7520b3c42145b3cb1b8c26477cdaed0521b02a0298907339fefa1).

## Steps to Reproduce the Problem

1. `wget https://github.com/bazelbuild/rules_fuzzing/archive/v0.2.0.zip`
1. `sha256sum v0.2.0.zip`

## Specifications

- Version: 0.2.0
- Platform: all

**Comment by stefanbucur** [comment]
> The given hash (9b688a77b930e1842312d37b00fbb796b96323a2eb8362b2cfb68e7d6e74f860) is for the release's .tar.gz file, not the .zip. 

You are absolutely right - this is exactly what happened. I computed the hash for the wrong file extension. Thanks for flagging this - fix is out in #173.
