### ISSUE TITLE
Feature: pass "--jobs"/"--fork" to jazzer engine

### ISSUE THREAD

**Issue by eustas** [bazelbuild/rules_fuzzing#175]
Currently it is not possible to ask (jazzer) fuzzer to employ the all CPUs / cores for fuzzing.

**Comment by fmeum** [comment]
Could you try https://github.com/bazelbuild/rules_fuzzing/commit/9775cd58b85a464e969e8a0734c7ffef28036583? That should allow you to pass arguments to the engines from the command line (but not from targets).

**Comment by eustas** [comment]
It works. Thanks.
