### ISSUE TITLE
Cut v0.3.0 release

### ISSUE THREAD

**Issue by stefanbucur** [bazelbuild/rules_fuzzing#190]
@fmeum I'm considering cutting a new release to incorporate the latest changes in HEAD (UBSan support, updated Jazzer support, GCC compatibility, better MacOS support). Is there anything else that you'd like to land soon before the release, or should I go ahead with it?

**Comment by fmeum** [comment]
You can go ahead. All the Jazzer bug fixes I wanted to get in were in the PR you just merged.

**Comment by stefanbucur** [comment]
Perfect, thanks a lot!

**Comment by stefanbucur** [comment]
I'm getting the following error when trying to run the Jazzer examples on my machine:

```sh
$ bazel test --build_tag_filters=fuzz-test --config=jazzer //examples/java/...
INFO: Analyzed 5 targets (0 packages loaded, 0 targets configured).
INFO: Found 5 test targets...
ERROR: /usr/local/google/home/sbucur/.cache/bazel/_bazel_sbucur/2527f57e21cfbf2e414b894f7610e705/external/jazzer/driver/BUILD.bazel:105:10: Linking external/jazzer/driver/jazzer_driver failed: (Exit 1): clang-10 failed: error executing command /usr/bin/clang-10 @bazel-out/k8-fastbuild/bin/external/jazzer/driver/jazzer_driver-2.params

Use --sandbox_debug to see verbose messages from the sandbox
clang: error: invalid linker name in argument '-fuse-ld=lld'
INFO: Elapsed time: 0.186s, Critical Path: 0.07s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
//examples/java:FuzzTest                                              NO STATUS
//examples/java:NativeFuzzTest                                        NO STATUS
//examples/java:NativeRunfileFuzzTest                                 NO STATUS
//examples/java:NativeUbsanFuncPtrFuzzTest                            NO STATUS
//examples/java:EmptyFuzzTest                                   FAILED TO BUILD

FAILED: Build did NOT complete successfully
```

Is there something wrong with my configuration? I can update the README file if needed.

**Comment by fmeum** [comment]
When build with clang on Linux, Jazzer uses lld instead of ld as the latter produces some warnings when used with LLVM sanitizers. I assumed everyone with clang on their machine to also have lld installed, but the issue you are experiencing makes it obvious that this isn't correct.

I will try to make Jazzer use ld instead tomorrow and report back.

**Comment by fmeum** [comment]
@stefanbucur What is the minimum Bazel version you would like rules_fuzzing to support?

**Comment by stefanbucur** [comment]
> When build with clang on Linux, Jazzer uses lld instead of ld as the latter produces some warnings when used with LLVM sanitizers. I assumed everyone with clang on their machine to also have lld installed, but the issue you are experiencing makes it obvious that this isn't correct.

Ah, good catch - indeed, after doing `apt-get install lld-10`, all the examples work correctly.

> 
> I will try to make Jazzer use ld instead tomorrow and report back.

Sounds good to me, but it's not a big issue to require lld either for Jazzer support, if for any reason the ld alternative turns to be cumbersome.

> @stefanbucur What is the minimum Bazel version you would like rules_fuzzing to support?

That's a good question - I'm not sure. In general, the earlier the version, the more users we can potentially support. But I also don't have a good picture of what versions are being used in the wild and in enterprises, so I am left with guessing :)

What is the oldest version known to work with the current Jazzer support? We could go with that as a starting point.

**Comment by fmeum** [comment]
With the system linker, I get the following warning when compiling Jazzer:
```
INFO: From Linking driver/jazzer_driver_asan:
/usr/bin/ld.gold: warning: Cannot export local symbol '__asan_extra_spill_area'
/usr/bin/ld.gold: warning: Cannot export local symbol '__lsan_current_stage'
```
I haven't been able to find out whether this means something is broken or not, but perhaps it's a good idea to stick with lld.

We are not testing with it in CI, but I just verified that Jazzer works with Bazel 4.0.0.

**Comment by stefanbucur** [comment]
This is now done.
