### ISSUE TITLE
Add support for test size/timeout in `cc_fuzz_test`.

### ISSUE THREAD

**Issue by iphydf** [bazelbuild/rules_fuzzing#202]
## Expected Behavior

Test success without warnings.

## Actual Behavior

```
ERROR: /src/workspace/c-toxcore/toxcore/BUILD.bazel:497:13: //c-toxcore/toxcore:group_moderation_fuzz_test_raw_: no such attribute 'size' in 'cc_binary' rule
```

## Steps to Reproduce the Problem

1. Add `cc_fuzz_test(... size = "small")`
1. `bazel build //...`
1. Profit. (or not)

## Specifications

- Version: v0.3.1
- Platform: Linux/x86_64, bazel 5.0.0.

**Comment by fmeum** [comment]
I just submitted #204, could you check whether that fixes the issue for you?
