### ISSUE TITLE
Question - Is there any plan to support fuzztest?

### ISSUE THREAD

**Issue by stonebrakert6** [bazelbuild/rules_fuzzing#230]
Sorry for the newbie question. Is support for [fuzztest](https://github.com/google/fuzztest), planned in the near future?

**Comment by stefanbucur** [comment]
I would be interested to know what specific features you have in mind here.

FWIW, the FuzzTest framework is already built using Bazel and FuzzTests are written as first-class `cc_test` rules (see [codelab example](https://github.com/google/fuzztest/blob/5018a2b72b3b7db067e32121996f0d12b8660dff/codelab/BUILD#L27-L35)), with support to [auto-generate .bazelrc configs](https://github.com/google/fuzztest/blob/5018a2b72b3b7db067e32121996f0d12b8660dff/bazel/setup_configs.sh).

**Comment by stonebrakert6** [comment]
Thanks @stefanbucur - I wasn't much familiar with fuzztest when I posted this question(just my impatience).  I think we can close this? I was exploring options to fuzz test my application back then. I've already integrated my application with fuzztest for fuzzing and I'm pretty happy with it. Thanks a lot for your help.

**Comment by stefanbucur** [comment]
Awesome, glad to hear this!

**Comment by dieortin** [comment]
@stefanbucur I'm curious, are there any advantages of this ruleset above FuzzTest for C++?
