### ISSUE TITLE
Default Java Fuzzer Example Fails

### ISSUE THREAD

**Issue by asudhak** [bazelbuild/rules_fuzzing#235]
## Expected Behavior
A straightforward fuzzing run from the example from the docs must succeed

## Actual Behavior
It fails with the following error when trying to run the simple Java Fuzzer.

```bazel run --config=jazzer //:JavaFuzzTest_run
ERROR: Projects/fuzz-sample/BUILD:3:15: in java_binary rule //:JavaFuzzTest_metadata_: need at least one of 'main_class' or Java source files
ERROR: Projects/fuzz-sample/BUILD:3:15: in java_binary rule //:JavaFuzzTest_metadata_: main_class was not provided and cannot be inferred: source path doesn't include a known root (java, javatests, src, testsrc)
ERROR: Projects/fuzz-sample/BUILD:3:15: Analysis of target '//:JavaFuzzTest_metadata_' failed
ERROR: Analysis of target '//:JavaFuzzTest_run' failed; build aborted:
INFO: Elapsed time: 13.079s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (72 packages loaded, 1459 targets configured)
ERROR: Build failed. Not running target
```
BUILD
```
load("@rules_fuzzing//fuzzing:java_defs.bzl", "java_fuzz_test")

java_fuzz_test(
    name = "JavaFuzzTest",
    srcs = ["src/com/example/JavaFuzzTest.java"],
    # target_class is not needed if using the Maven directory layout.
    # target_class = "com.example.JavaFuzzTest",
)
```

## Steps to Reproduce the Problem

1. Follow instructions from https://github.com/bazelbuild/rules_fuzzing#java-fuzzing
2. Run `bazel run --config=jazzer //:JavaFuzzTest_run`

## Specifications
- Version: bazel 6.3.2-homebrew
- Platform: macOS

**Comment by asudhak** [comment]
Ignore the above comment, I used the wrong target. works as expected with the change.

**Comment by fmeum** [comment]
> Ignore the above comment, I used the wrong target. works as expected with the change.

Just for the sake of posterity: You need to `bazel run //:JavaFuzzTest_run`. Glad that you figured it out!
