### ISSUE TITLE
Update CI to use clang-10 with bazel

### ISSUE THREAD

**Issue by asraa** [bazelbuild/rules_fuzzing#28]
## Expected Behavior
Build FuzzedDataProvider tests in CI build test by finding a way for bazel to use clang-10

## Actual Behavior
Right now, FDP test is skipped because bazel builds with clang-9

**Comment by stefanbucur** [comment]
This is now fixed: https://github.com/bazelbuild/rules_fuzzing/blob/e611b02d7bb4b44a8b073980793eb15751cfaa4b/.bazelrc#L16-L17
